# Generated by Django 5.2.4 on 2025-08-11 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='delete_time',
        ),
        migrations.RemoveField(
            model_name='goodscategory',
            name='delete_time',
        ),
        migrations.RemoveField(
            model_name='goodschannel',
            name='delete_time',
        ),
        migrations.RemoveField(
            model_name='goodschannelgroup',
            name='delete_time',
        ),
        migrations.RemoveField(
            model_name='sku',
            name='delete_time',
        ),
        migrations.RemoveField(
            model_name='skuimage',
            name='delete_time',
        ),
        migrations.RemoveField(
            model_name='skuspecification',
            name='delete_time',
        ),
        migrations.RemoveField(
            model_name='specificationoption',
            name='delete_time',
        ),
        migrations.RemoveField(
            model_name='spu',
            name='delete_time',
        ),
        migrations.RemoveField(
            model_name='spuspecification',
            name='delete_time',
        ),
    ]
