# Generated by Django 5.2.4 on 2025-08-07 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauthqquser',
            name='delete_time',
            field=models.DateTimeField(default=None, verbose_name='删除时间'),
        ),
    ]
