# Generated by Django 5.2.4 on 2025-08-11 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0002_alter_oauthqquser_delete_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oauthqquser',
            name='delete_time',
        ),
    ]
