# Generated by Django 5.2.4 on 2025-08-11 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='delete_time',
        ),
        migrations.RemoveField(
            model_name='contentcategory',
            name='delete_time',
        ),
    ]
