# Generated by Django 5.2.4 on 2025-08-11 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_options_alter_user_mobile_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='delete_time',
        ),
    ]
